name: .NET

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create Issue on Test Failure
      if: failure()
      uses: JasonEtco/create-an-issue@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Test Failed"
        body: "One or more tests have failed. Please review the test results and fix the issues."
