name: .NET Dev

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create Pull Request
      if: success()
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automated PR: Test Passed"
        branch: dev
        base: main
        title: "Automated PR: Test Passed"
        body: "This PR was automatically created by GitHub Actions because all tests passed."
